/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PkCodeView: typeof import('./components/pk-code-view/index.vue')['default']
    PkSvgIcon: typeof import('./components/pk-svg-icon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableLayout: typeof import('./components/table-layout/index.vue')['default']
  }
}
